TEST_VALUE:
  name: cookie
MONGODB_CONFIG:
  name: "campus-organization-system"          # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb://localhost:27017"   # 数据库链接地址
#  username: "xxxx"                   # 数据库链接用户名
#  password: "123456"                 # 数据库链接密码
  database: "COS-DB"      # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: true                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能
#  弃用警告：当前服务器发现和监视引擎已弃用，将在将来的版本中删除。
#  要使用新的服务器发现和监视引擎，请将选项{useUnifiedTopology:true}传递给mongoClient构造函数。
  useUnifiedTopology: true
# https://blog.csdn.net/qq_30678943/article/details/125675108
REDIS_CONFIG:
  host: "localhost"  # redis 链接
  port: 6379         # redis 端口
#  auth: "xxxx"       # redis 连接密码
  db: 1              # redis 数据库
EMAIL_CONFIG:
  service: "qq"
  port: 465
  secureConnection: true
  auth:
    user: 'ryan.jiang@foxmail.com'
    pass: 'cwblxgtienytdecd'